### ISSUE TITLE
Notice on a fresh install

### ISSUE THREAD

**Issue by Da-Fecto** [IDT-media/Pages2JSON#2]
On a fresh install of the module a notice is thrown:
**( ! ) Notice: Undefined index: fields in /tralal/site/modules/Pages2JSON/Pages2JSON.module on line 103**

```
// Changed to the line below solves it for now
$displayFields->value = isset($data['fields']) ? $data['fields'] : array();
```

**Comment by Stikki** [comment]
Alright, haven't actually uninstalled / installed module while development cycle, so explains.

Thanks for there info, i'll look into it when i find some time.

**Comment by Da-Fecto** [comment]
No problem.... take your time... I went an other route as that fits better in the scope of my current project.

**Comment by Stikki** [comment]
This issue was fixed, as far i know, lemme know if this still occurs, thanks for participating.
