### ISSUE TITLE
How to get the rootParent of a Page?

### ISSUE THREAD

**Issue by jmartsch** [IDT-media/Pages2JSON#4]
How can I get the rootParent of a page in the JSON Object?
This field/property is not selectable in the module config.

I think this can be done with hooking Pages2JSON::getFields, but I don´t know how.
Can you tell me how to do this?

**Comment by Stikki** [comment]
It's core static attribute, which is missing from the list, will add it at some point to statics

you can manipulate fields like this:

```
 // Add ghost fields to these templates.
wire()->addHookAfter('Pages2JSON::getFields', function($event) {
	
	$page = $event->arguments(0);
	
	// Add virtual fields that trigger Page::getUnknown()
	$fields = $event->return;
	$fields[] = 'normal_price';
	$fields[] = 'sales_price';

	$event->return = $fields;

});
```

**Comment by jmartsch** [comment]
I solved this quick and dirty by just modifying the toPage function, and adding `$obj->rootParent = $page->rootParent()->title;` to it:

```
protected function toPage(Page $page)
        {
            $obj = new stdClass();
            $fields = $this->getFields($page);
            $fields = array_merge($fields, (array)$page->template->jsonFields);

            foreach ($fields as $field) {

                $value = $this->getValue($page->$field);

                if (!is_null($value))
                    $obj->$field = $value;
            }
            $obj->rootParent = $page->rootParent()->title;

            return $obj;
        }
```

**Comment by jmartsch** [comment]
Your solution is great for fields that really exist. But rootParent is a function that is being called. So i could not use your provided solution.

**Comment by Stikki** [comment]
But you can simply add rootParent to statics:

```
	#---------------------
	# Attributes
	#---------------------	

	static protected $static_fields = array(
		'id', 
		'name', 
		'url',
		'httpUrl',
		'template', 
		'parent', 
		'parent_id', 
		'rootParent',
		'created', 
		'modified', 
		'created_users_id', 
		'modified_users_id',
		'status'
	);
```
Then configure root page to have "title" as defined JSON output and that's it?
